# Generated by Django 3.2.5 on 2022-11-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_departmentmodel_dept_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='email',
        ),
    ]
