# Generated by Django 3.2.5 on 2022-11-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_employeemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DepartmentModel',
        ),
    ]
